# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        sudo apt install libatlas-base-dev
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build API Image
      run: |
        ls
        RELEASE_TAG=$(echo $GITHUB_REF | cut -d '/' -f3)
        echo $RELEASE_TAG > .version
        docker login docker.pkg.github.com --username mikkokotila --password ${{ secrets.MIKKOKOTILA_TOKEN }}
        docker build -t docker.pkg.github.com/mikkokotila/Padma/core_api:$RELEASE_TAG -f ./Dockerfile .
        docker push docker.pkg.github.com/mikkokotila/Padma/core_api:$RELEASE_TAG
    - name: Test
      run: |
        #gunicorn --bind 0.0.0.0:5000 server:app --daemon
        #sleep 10
        #python ./tests.py
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 18.157.93.60
        username: ubuntu
        key: ${{ secrets.PADMA }}
        command_timeout: 5m
        script: |
          cd Padma
          git pull https://github.com/mikkokotila/Padma.git
          sudo systemctl restart Padma
