name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build API Image
      run: |
        docker login docker.pkg.github.com --username mikkokotila --password ${{ secrets.MIKKOKOTILA_TOKEN }}
        docker build -t docker.pkg.github.com/mikkokotila/padma/core_api:master -f ./Dockerfile .
        docker push docker.pkg.github.com/mikkokotila/padma/core_api:master
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 18.157.93.60
        username: ubuntu
        key: ${{ secrets.PADMA }}
        command_timeout: 5m
        script: |
          sudo docker system prune -f
          RUNNING_IMAGE=$(sudo docker ps | grep server | cut -d ' ' -f1)
          sudo docker login docker.pkg.github.com --username mikkokotila --password ${{ secrets.MIKKOKOTILA_TOKEN }}
          sudo docker pull docker.pkg.github.com/mikkokotila/padma/core_api:master
          NEW_IMAGE_ID=$(sudo docker images | grep core_api | head -1 | tr -s ' ' | cut -d ' ' -f3)

          if [ ${#RUNNING_IMAGE} -gt 1 ]
          then
            sudo docker stop $RUNNING_IMAGE
          fi
          
          sudo docker run --restart unless-stopped -v /tmp/Padma:/tmp -p 5000:5000 $NEW_IMAGE_ID --name Padma-API --detached;
    - name: Production Test
      uses: appleboy/ssh-action@master
      with:
        host: 18.158.207.5
        username: ubuntu
        key: ${{ secrets.PADMA }}
        command_timeout: 5m
        script: |
          curl https://raw.githubusercontent.com/mikkokotila/Padma/master/tests/deploy_tests.py > deploy_tests.py
          chmod +x deploy_tests.py
          python3 deploy_tests.py
